bot:
  name: chitchatnad_bot
  token: 6190905268:AAEjx3R54ClCIlQFp0Q5TawF0-pxmu6thZI
#  name: atvxkb_bot
#  token: 6093951131:AAGOAxZbjGWFTRphA_fYeQcXF2vxmkbTi6I

spring:
  datasource:
    username: postgres
    password: 7272
    url: jdbc:postgresql://localhost:5432/chat_bot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
#
#  main:
#    allow-circular-references: true
server:
  port: 8181

private:
  group:
    id: -940378976